### ISSUE TITLE
Base64 images

### ISSUE THREAD

**Issue by Chaoste** [jankovicsandras/imagetracerjs#10]
Hi,

I'm using your tool and I like it a lot!
But in my current application I'm receiving 4 imagesfrom the backend at one time. Because this is not that easy I decided to send those images as base64 images in a json object. I'm not able to store the base64 data as image in the frontend (because browsers don't allow me to do that) so I need to find a direct way to convert base64 image to svg.
Is there any possibility to do this?

Greetings,
Thomas

**Comment by jankovicsandras** [comment]
Hi,

I'm happy to hear that you find imagetracerjs useful. :)

Please clarify what you mean by "I'm not able to store the base64 data as image in the frontend (because browsers don't allow me to do that)" ? If the client browser supports [Data URI](http://caniuse.com/#search=data%20uri)s and [Canvas](http://caniuse.com/#search=canvas) then you can probably do something like this:

```javascript
// Let's say you got the JSON object with the 4 Base64 strings from the server, which looks something like this:
// jsonobj = [ 'abcBlabla...' , 'bcdBlabla...' , 'cdeBlabla...' , 'defBlabla...' ]; 

// Tracing the first Base64 encoded image from jsonobj
ImageTracer.imageToSVG(

	'data:image/jpeg;base64,'+jsonobj[0], // Image source: Data URI with Base64; you might need 'data:image/png;base64,'  instead

	function(svgstr){ ImageTracer.appendSVGString( svgstr, 'svgcontainer' ); }, // What to do with the result SVG string: append to a container <div>

	'Posterized2' // How to trace: 'Posterized2' option preset
);
```

If you can't do this, then you get (JPEG or PNG or similar) bytestreams when you Base64 decode the JSON strings. So you need some JavaScript library that can decompress these into [ImageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData) (which is basically raw RGBA pixel data as a byte array + width and height). Then you can trace the ImageData object.

You might consider tracing the images on the backend (this is possible if you can use Node.js or Java on the server) and sending the SVG strings in the JSON object (no Base64 encoding needed). 

Best wishes,
András

**Comment by jankovicsandras** [comment]
Please reopen this issue if this doesn't work.

**Comment by Chaoste** [comment]
Thank you for your clarifications. If I can check your example if it works for me, I'll will write you. In the beginning I thought your framework is not able to parse a base64 string and only reads from files. And I couldn't fing anything by googling about how to store multiple images as files without the user noticing it which I think shouldn't be possible so I won't have image files but only those base64 images.

Thanks for the idea of converting on the backend side. I'll test this, too.
