### ISSUE TITLE
Creating plotter-path possible?

### ISSUE THREAD

**Issue by ld21** [jankovicsandras/imagetracerjs#37]
Hi – I like your code, very fascinating. I'm would like to build a simle plotter run by an ESP32 that receives it's drawing path from an SVG calculated by the browser. Since I'm not familiar with all the options you have in your imagetracerjs, could you recommend options so that I would get something as can be seen in the picture below? Thank you very much, Dani

![original_and_traced_version](https://user-images.githubusercontent.com/4065975/75659750-ca631000-5c6a-11ea-8601-59e14bd78633.png)
Left: Original, pixelbased photo / Right: Calculated SVG

For this project, I was inspired by [https://www.brachiograph.art/](https://www.brachiograph.art/).

**Comment by jankovicsandras** [comment]
Hi,

Yes, it's possible. As I understand, the [ESP32 plotter](https://github.com/bdring/midTbot_esp32) uses [G-code](https://en.wikipedia.org/wiki/G-code) . The simplest solution is translating SVG draw commands directly to G-code commands. I found this [https://github.com/em/gcanvas](https://github.com/em/gcanvas) which can convert canvas draw commands. It should be very easy to adapt to ImageTracer, since ImageTracer uses only [SVG paths and only M, L, Q and Z commands](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths
).

This might not be optimal for a BrachioGraph-like arm-writer, but it's a good start.

**Comment by jankovicsandras** [comment]
I hope this helped. Feel free to reopen this Issue if you have more questions.
