### ISSUE TITLE
Provide "bin" in package.json

### ISSUE THREAD

**Issue by der-On** [jankovicsandras/imagetracerjs#41]
To make usage of the nodecli easier you should provide a `bin` in the package.json pointing to the `nodecli/nodecli.js`

https://docs.npmjs.com/files/package.json#bin

This way we then can do:

``
$ npm install -g imagetracerjs
$ imagtracerjs ...
```

**Comment by jankovicsandras** [comment]
Hi,

Thanks for your advice! It's a good idea, it would be easier to use ```nodecli``` this way.

But I will postpone this change because ```nodecli``` is not meant to be an application right now. It's only meant to be a simple example. It's also dependent on external libraries, and I don't consider the PNG loader included in the package to be a part of the ImageTracer project. I recommend everybody to find the most suitable canvas/Imagedata loader on Node.js. I hope you understand my reasons.

I will consider this in the future, when the ```nodecli``` will be developed further.
