### ISSUE TITLE
Feature: centerline tracing

### ISSUE THREAD

**Issue by Zireael07** [jankovicsandras/imagetracerjs#65]
Title.

**Comment by jankovicsandras** [comment]
Hi,

Can you please give me some details on your idea? Do you mean starting the shape at the approx. top-center?

**Comment by Zireael07** [comment]
No, literally tracing lines by their center. What this program does https://autotrace.sourceforge.net (Inkscape uses it under the hood when you tick the centerline option in Trace Bitmap)

**Comment by jankovicsandras** [comment]
I thought about this and checked Autotrace. It's a good idea, so I added it to the [Ideas for improvement list](https://github.com/jankovicsandras/imagetracerjs/blob/master/process_overview.md#ideas-for-improvement).
However, ImageTracer uses a different algorithm, which can't be easily upgraded to support centerline tracing. I estimate it would take minimum 2x the current size and complexity, because a new algorithm is needed after layer separation. Sadly I don't have the time to work on this now.

**Comment by Zireael07** [comment]
Fine, that's understandable. (I didn't check the algorithms themselves, tbh)
